server:
  servlet:
    context-path: /api/v1
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    static-path-pattern: /static/**

  data:
    rest:
      detection-strategy: annotated
